name: flutter_flexible_toast
description: A Powerful Toast Library for Flutter, Easily create toast messages in single line of code with leading image options.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  pedantic: ^1.11.0



flutter:
  plugin:
    androidPackage: sanketvekariya.flutter_flexible_toast
    pluginClass: FlutterFlexibleToastPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - images/

